name: Build and Deploy Flutter Webview App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # Or 'beta', 'dev' or 'master'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign
          cd ios
          export CODESIGNING_FOLDER=$(flutter config --enable-ios-codesigning --output-dir)
          export IPA_OUTPUT_PATH=$CODESIGNING_FOLDER/Runner.ipa
          fastlane build_app
          cp $IPA_OUTPUT_PATH ../build/ios/app.ipa
        working-directory: ./flutter_project

      - name: Build Android APK
        run: flutter build apk --release
        working-Coefficient: ./flutter_project

      - name: Deploy to App Store and Google Play
        uses: wzieba/Deploy-Flutter-App@v1
        with:
          ios-distribution-certificate: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE }}
          ios-distribution-provisioning-profile: ${{ secrets.IOS_DISTRIBUTION_PROVISIONING_PROFILE }}
          ios-app-identifier: ${{ secrets.IOS_APP_IDENTIFIER }}
          google-play-json-base64: ${{ secrets.GOOGLE_PLAY_JSON }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
