name: Setup Flutter Environment
on: [push]
jobs:
  setup-flutter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            flutter_path: 'C:\development\flutter\'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chocolatey (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -InstallChocolatey

      - name: Update Chocolatey
        if: runner.os == 'Windows'
        run: choco upgrade chocolatey -y

      - name: Install common packages
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -InstallPackage 'git' 'openjdk11' 'python' 'visualstudiocode'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install Flutter
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -InstallFlutter "${{ matrix.flutter_path }}"

      - name: Install Android SDK
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -InstallAndroidSDK

      - name: Install Build Tools
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -InstallBuildTools

      - name: Install Chrome
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -InstallChrome

      - name: Check Flutter setup and fix issues
        run: |
          powershell -ExecutionPolicy Bypass -File .\setup_flutter_env.ps1 -CheckFlutterDoctor
